import type { Product } from "@/types/product";

/**
 * Seed data – used during development and for unit tests.
 * In production this data lives in the database.
 */
export const SEED_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Classic Chino Trousers",
    slug: "classic-chino-trousers",
    description: "Smart, versatile chinos perfect for school or casual wear.",
    brand: "KidsFit",
    category: "boys-trousers",
    imageUrl: "/images/boys-trousers/classic-chino.jpg",
    variants: [
      {
        id: 1,
        productId: 1,
        ageRange: "4-5Y",
        waistSize: "45cm",
        length: "Regular",
        material: "Cotton",
        color: "Beige",
        fit: "Regular",
        price: 14.99,
        stock: 20,
        sku: "CHN-4-5-45-REG-COT-BEI",
      },
      {
        id: 2,
        productId: 1,
        ageRange: "6-7Y",
        waistSize: "50cm",
        length: "Regular",
        material: "Cotton",
        color: "Navy",
        fit: "Regular",
        price: 15.99,
        stock: 15,
        sku: "CHN-6-7-50-REG-COT-NAV",
      },
    ],
  },
  {
    id: 2,
    name: "Slim Denim Jeans",
    slug: "slim-denim-jeans",
    description: "Durable stretch denim jeans with adjustable waistband.",
    brand: "DenimCo",
    category: "boys-trousers",
    imageUrl: "/images/boys-trousers/slim-denim.jpg",
    variants: [
      {
        id: 3,
        productId: 2,
        ageRange: "8-9Y",
        waistSize: "55cm",
        length: "Regular",
        material: "Denim",
        color: "Blue",
        fit: "Slim",
        price: 19.99,
        stock: 10,
        sku: "DNM-8-9-55-REG-DEN-BLU",
      },
      {
        id: 4,
        productId: 2,
        ageRange: "10-11Y",
        waistSize: "60cm",
        length: "Long",
        material: "Denim",
        color: "Black",
        fit: "Slim",
        price: 22.99,
        stock: 8,
        sku: "DNM-10-11-60-LNG-DEN-BLK",
      },
    ],
  },
  {
    id: 3,
    name: "Relaxed Linen Trousers",
    slug: "relaxed-linen-trousers",
    description: "Lightweight linen trousers, ideal for summer.",
    brand: "SummerKids",
    category: "boys-trousers",
    imageUrl: "/images/boys-trousers/linen-trousers.jpg",
    variants: [
      {
        id: 5,
        productId: 3,
        ageRange: "2-3Y",
        waistSize: "40cm",
        length: "Short",
        material: "Linen",
        color: "White",
        fit: "Relaxed",
        price: 12.99,
        stock: 25,
        sku: "LIN-2-3-40-SHT-LIN-WHT",
      },
      {
        id: 6,
        productId: 3,
        ageRange: "4-5Y",
        waistSize: "45cm",
        length: "Short",
        material: "Linen",
        color: "Khaki",
        fit: "Relaxed",
        price: 13.99,
        stock: 18,
        sku: "LIN-4-5-45-SHT-LIN-KHK",
      },
    ],
  },
  {
    id: 4,
    name: "Smart Wool Blend Trousers",
    slug: "smart-wool-blend-trousers",
    description: "Warm wool-blend trousers for school and formal occasions.",
    brand: "KidsFit",
    category: "boys-trousers",
    imageUrl: "/images/boys-trousers/wool-trousers.jpg",
    variants: [
      {
        id: 7,
        productId: 4,
        ageRange: "12-13Y",
        waistSize: "65cm",
        length: "Long",
        material: "Wool Blend",
        color: "Grey",
        fit: "Regular",
        price: 29.99,
        stock: 5,
        sku: "WOL-12-13-65-LNG-WOL-GRY",
      },
    ],
  },
  {
    id: 5,
    name: "Jogger Track Trousers",
    slug: "jogger-track-trousers",
    description: "Comfortable polyester joggers with elastic waistband.",
    brand: "ActiveKids",
    category: "boys-trousers",
    imageUrl: "/images/boys-trousers/jogger-trousers.jpg",
    variants: [
      {
        id: 8,
        productId: 5,
        ageRange: "6-7Y",
        waistSize: "50cm",
        length: "Regular",
        material: "Polyester",
        color: "Grey",
        fit: "Relaxed",
        price: 11.99,
        stock: 30,
        sku: "JOG-6-7-50-REG-POL-GRY",
      },
      {
        id: 9,
        productId: 5,
        ageRange: "8-9Y",
        waistSize: "55cm",
        length: "Regular",
        material: "Polyester",
        color: "Black",
        fit: "Relaxed",
        price: 12.99,
        stock: 22,
        sku: "JOG-8-9-55-REG-POL-BLK",
      },
    ],
  },
];
